### ISSUE TITLE
Error in TGM plugin activation envato theme check plugin

### ISSUE THREAD

**Issue by VikasKuk123** [itspriddle/wp-cli-tgmpa-plugin#32]
Hello

i have installed wordpress 4.9.5 version and installed TGM plugin activation plugin and i got error in envato theme check plugin.
![capture2](https://user-images.githubusercontent.com/38753029/39299066-7fb99692-4965-11e8-9f5f-6deaf6c84b65.PNG)

please find attached image for error.

please help me for resolve this error

**Comment by itspriddle** [comment]
Your error seems unrelated to this project. This plugin is a [WP-CLI](https://wp-cli.org) plugin used for installing plugins managed with TGMPA.

The "WARNING" in your screenshot can likely be ignored if you are certain your `remove_filter()` calls are valid, and the "REQUIRED" suggests that you can use `function_exists()` or `class_exists()` instead of `is_plugin_active()`. These issues are almost certainly related to your theme code and not to TGMPA.
